version: '3.8'

services:
  # Laravel
  laravel-app:
    build:
      context: ./task_management
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./task_management:/var/www
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - app-network

  # React
  react-frontend:
    build:
      context: ./task_management/frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    command: npm run dev
    working_dir: /app
    volumes:
      - ./task_management/frontend:/app
      - /app/node_modules
    networks:
      - app-network
    stdin_open: true
    tty: true

  # PostgreSQL
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: intermilan12
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
